#targets:
#  $default:
#    builders:
#      artemis:
#        options:
#          schema_mapping:
#            - schema: lib/schema.graphql
#              queries_glob: lib/queries/article.query.graphql
#              output: lib/graphql/article.query.dart
#          custom_parser_import: 'package:catalog/coercers.dart'
#          scalar_mapping:
#            - graphql_type: Time
#              dart_type: DateTime
#              use_custom_parser: true
targets:
  $default:
    builders:
      artemis:
        options:
          schema_mapping:
            - output: lib/graphql/queries/medee.dart
              schema: lib/graphql/schema.graphql
              queries_glob: lib/graphql/querySchema/medee.query.graphql
            - output: lib/graphql/queries/shuurhai_ajil.dart
              schema: lib/graphql/schema.graphql
              queries_glob: lib/graphql/querySchema/shuurhai_ajil.query.graphql
            - output: lib/graphql/queries/zg_hotolbor.dart
              schema: lib/graphql/schema.graphql
              queries_glob: lib/graphql/querySchema/zg_hotolbor.query.graphql
            - output: lib/graphql/queries/huuli_togtoolmj.dart
              schema: lib/graphql/schema.graphql
              queries_glob: lib/graphql/querySchema/huuli_togtoolmj.query.graphql
            - output: lib/graphql/queries/statistic_medee.dart
              schema: lib/graphql/schema.graphql
              queries_glob: lib/graphql/querySchema/statistic_medee.query.graphql
            - output: lib/graphql/queries/heregjilt_guitsetgel.dart
              schema: lib/graphql/schema.graphql
              queries_glob: lib/graphql/querySchema/heregjilt_guitsetgel.query.graphql
            - output: lib/graphql/queries/tusuv_hudav_ajilgaa.dart
              schema: lib/graphql/schema.graphql
              queries_glob: lib/graphql/querySchema/tusuv_hudav_ajilgaa.query.graphql
            - output: lib/graphql/queries/tusulvvdiin_medeelel.dart
              schema: lib/graphql/schema.graphql
              queries_glob: lib/graphql/querySchema/tusulvvdiin_medeelel.query.graphql
            - output: lib/graphql/queries/busad.dart
              schema: lib/graphql/schema.graphql
              queries_glob: lib/graphql/querySchema/busad.query.graphql
            - output: lib/graphql/queries/common.dart
              schema: lib/graphql/schema.graphql
              queries_glob: lib/graphql/querySchema/common.query.graphql
            - output: lib/graphql/queries/tzAndSongon.dart
              schema: lib/graphql/schema.graphql
              queries_glob: lib/graphql/querySchema/tzAndSongon.query.graphql



          custom_parser_import: 'package:catalog/graphql/utils/coercers.dart'
          scalar_mapping:
            - graphql_type: Time
              dart_type: DateTime
              use_custom_parser: true
            - graphql_type: Date
              dart_type: DateTime
              use_custom_parser: true
            - graphql_type: ID
              dart_type: int
              use_custom_parser: false