#targets:
#  $default:
#    builders:
#      artemis:
#        options:
#          schema_mapping:
#            - schema: lib/schema.graphql
#              queries_glob: lib/queries/article.query.graphql
#              output: lib/graphql/article.query.dart
#          custom_parser_import: 'package:catalog/coercers.dart'
#          scalar_mapping:
#            - graphql_type: Time
#              dart_type: DateTime
#              use_custom_parser: true
targets:
  $default:
    builders:
      gql_build|ast_builder:
        enabled: false
      gql_build|req_builder:
        enabled: true
        options:
          schema: catalog|lib/graphql/schema.graphql
      gql_build|serializer_builder:
        enabled: false
        options:
          schema: catalog|lib/graphql/schema.graphql
      gql_build|schema_builder:
        enabled: true
      gql_build|data_builder:
        enabled: true
        options:
          schema: catalog|lib/graphql/schema.graphql
      gql_build|var_builder:
        enabled: false
        options:
          schema: catalog|lib/graphql/schema.graphql
#targets:
#  $default:
#    builders:
#      artemis:
#        options:
#          schema_mapping:
#            - output: lib/graphql/queries/medee.dart
#              schema: lib/graphql/schema.graphql
#              queries_glob: lib/graphql/querySchema/medee.query.graphql
#
#          custom_parser_import: 'package:catalog/graphql/utils/coercers.dart'
#          scalar_mapping:
#            - graphql_type: Time
#              dart_type: DateTime
#              use_custom_parser: true
#            - graphql_type: ID
#              dart_type: int
#              use_custom_parser: false