name: catalog
description: catalog

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.5+5

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  lambda:
    path: ./lambda
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  url_launcher: ^5.0.2
  shared_preferences: ^0.5.3+4
  dio: 3.0.9
  provider: 4.0.4
  get_it: 4.0.0
  flutter_map: 0.8.2
  font_awesome_flutter: 8.8.1
  awesome_dialog: 1.3.0
  flutter_inner_drawer: ^0.4.0
  device_info: 0.4.2+2
  local_auth: 0.6.1+3
  flutter_icons: ^0.1.4
  flutter_secure_storage: ^3.3.5
  gestures: 0.0.1
  flutter_swiper: ^1.1.6
  intro_views_flutter: ^2.8.0
  liquid_progress_indicator: 0.3.2
  flushbar: 1.10.0
  validators: ^2.0.0+1
  percent_indicator: ^2.1.1
  datetime_picker_formfield: 1.0.0
  date_format: 1.0.8
  petitparser: ^3.1.0
  image_picker: 0.6.7+11
  permission_handler: 4.4.0
  searchable_dropdown: 1.1.2
  flutter_offline: ^0.3.0
  dio_http_cache: 0.2.6
  sqflite: ^1.1.6+5
  flutter_staggered_grid_view: ^0.3.0
  flutter_svg: 0.18.0
  flutter_html: ^0.11.0
  package_info: 0.4.0+18
  carousel_slider: ^2.2.1
  flutter_launcher_name: ^0.0.1
  simple_animations: ^2.2.1
  meta: ^1.2.4
  gql: ^0.12.4
  equatable: ^1.2.5
  json_annotation: ^3.1.1
  intl: ^0.16.1
  jiffy: ^3.0.1
  flutter_echarts: 1.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "0.7.4"
  artemis: ^6.18.4
  build_runner: ^1.10.11
  json_serializable: ^3.5.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/uuhvy_img/1024x1024.png"

flutter_launcher_name:
  name: "УУХҮЯ"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/baseMaps/googleStreets.jpg
    - assets/images/baseMaps/googleSatellite.jpg
    - assets/images/baseMaps/tempimagery.jpg
    - assets/images/baseMaps/openstreet.jpg
    - assets/images/qr.png
    - assets/images/homebg.svg
    - assets/images/send.jpg
    - assets/images/register.png
    - assets/images/password.png
    - assets/images/mark.png
    - assets/uuhvy_img/yam.png
    - assets/uuhvy_img/uurhai.png
    - assets/uuhvy_img/ver_logo.png
    - assets/uuhvy_img/uurkhai.png
    - assets/uuhvy_img/barilga.png
    - assets/uuhvy_img/yamnii.png
    - assets/uuhvy_img/vildver.svg
    - assets/uuhvy_img/to.png
    - assets/uuhvy_img/zg.png
    - assets/uuhvy_img/chart.png
    - assets/uuhvy_img/chart1.svg
    - assets/uuhvy_img/auto_teever.svg
    - assets/uuhvy_img/tumur_zam.svg
    - assets/uuhvy_img/placeholder.png




  fonts:
    - family: Roboto-Condensed
      fonts:
        - asset: assets/fonts/Roboto_Condensed/RobotoCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto_Condensed/RobotoCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto_Condensed/RobotoCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto_Condensed/RobotoCondensed-BoldItalic.ttf
          weight: 700
          style: italic
    - family: EsriIcons
      fonts:
        - asset: assets/fonts/Esri/EsriIcons.ttf
          weight: 400
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
